# Generated by Django 4.2.7 on 2023-12-18 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminactions',
            name='response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
