version: '3'
services:
  postgres_server:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: Home-Service-App-Db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  home_services_dango_app:
    build: .
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres_server
    environment:
      DEBUG: 1
      DB_NAME: Home-Service-App-Db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: postgres_server
      DB_PORT: 5432

volumes:
  postgres_data: