# Generated by Django 4.2.7 on 2023-12-19 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_service_created_at_service_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='average_rating',
        ),
    ]
