# Generated by Django 4.2.7 on 2023-12-19 17:35

import cloudinary.models
from django.db import migrations
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_remove_service_average_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='sample_image',
            field=cloudinary.models.CloudinaryField(default=django.utils.timezone.now, max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
    ]
