# Generated by Django 4.2.7 on 2023-12-19 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.IntegerField(choices=[('ON_GOING', 'on-going'), ('COMPLETED', 'completed')]),
        ),
    ]
