# Generated by Django 4.2.7 on 2023-12-19 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('ON_GOING', 'on-going'), ('COMPLETED', 'completed')], default='ON_GOING', max_length=9),
        ),
    ]
