# Generated by Django 4.2.7 on 2023-12-19 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_alter_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('On Going', 'on-going'), ('Completed', 'completed')], default='On Going', max_length=9),
        ),
    ]
