# Generated by Django 4.2.7 on 2023-12-20 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_booking_booking_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='booking_end_date',
        ),
    ]
