name: Deploy to EC2

on:
  workflow_run:
    workflows: ["Docker Push Image to ECR"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup AWS EC2 Details
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Pull latest Docker image from ECR
        run: |
          ECR_REGISTRY=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.AWS_ECR_REPO }}
          IMAGE_TAG=${{ github.sha }}

          docker pull $ECR_REGISTRY:latest-$IMAGE_TAG

      - name: Deploy to EC2
        run: |
          ssh -i ./SSH.pem ec2-user@3.26.189.110 "docker stop home_services_app || true"
          ssh -i ./SSH.pem ec2-user@3.26.189.110 "docker rm home_services_app || true"
          ssh -i ./SSH.pem ec2-user@3.26.189.110 "docker run -d --name home_services_app -p 80:80 $ECR_REGISTRY/$ECR_REPOSITORY:latest-$IMAGE_TAG"