name: Docker Push Image to ECR
on: 
  push: 
    branches: [ "main" ]
  
jobs:
  Docker-Push:
    name: Build Docker Image & Push to ECR
    runs-on: ubuntu-latest  
    steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Setup AWS ECR Details
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{secrets.AWS_REGION}}

        - name: Login to Amazon ECR
          id: login-ecr
          uses: aws-actions/amazon-ecr-login@v1          

        - name: Build and push the tagged docker image to Amazon ECR
          env:
            ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
            ECR_REPOSITORY: ${{ secrets.AWS_ECR_REPO }}
            IMAGE_TAG: ${{ github.sha }}
          run: |
            docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:latest-$IMAGE_TAG .
            docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest-$IMAGE_TAG