name: Docker Push Image to ECR
on: 
  push: 
    branches: [ "main" ]
  
jobs:
  Docker-Push:
    name: Build Docker Image & Push to ECR
    runs-on: ubuntu-latest  
    steps:
        - name: Setup Docker
          uses: docker/setup-docker@v2
          with:
            version: 'latest'

        - name: Checkout
          uses: actions/checkout@v2    
          
        - name: Debug AWS Region
          run:  | 
            echo "AWS_REGION: ${{ secrets.AWS_REGION }}"

        - name: Setup AWS ECR Details
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{secrets.AWS_REGION}}

        - name: Login to Amazon ECR
          id: login-pf-aws-ecr
          uses: aws-actions/amazon-ecr-login@v1          

        - name: Build and push the tagged docker image to Amazon ECR
          env:
            ECR_REGISTRY: ${{ secrets.AWS_ECR_REGISTRY }}
            ECR_REPOSITORY: ${{ secrets.AWS_ECR_REPO }}
            IMAGE_TAG: latest
          run: |
            docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        
        - name: Retry Docker Push
          run: |
            retries=5
            until docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG || [ $retries -eq 0 ]; do
              sleep 15
              retries=$((retries-1))
            done
