name: CD - Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to AWS ECR
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registry: ${{ secrets.AWS_REGISTRY_URL }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Pull Docker image from ECR
        run: docker pull ${{ secrets.AWS_REGISTRY_URL }}/}/main:latest:latest

      - name: Deploy to EC2
        run: |
          # Copy necessary files to EC2 using SCP
          scp -i ${{ github.workspace }}/SSH.pem -r docker-compose.yml ec2-user@3.25.168.4:/home/ec2-user/my-django-app

          # SSH into EC2 and run Docker Compose commands
          ssh -i ${{ github.workspace }}/SSH.pem ec2-user@3.25.168.4 "cd /home/ec2-user/my-django-app && docker-compose down && docker-compose pull && docker-compose up -d"
